### ISSUE TITLE
createNamespacedPod not work ! but i use command kubectl apply -f test.yml it's work

### ISSUE THREAD

**Issue by taotao7** [kubernetes-client/javascript#1346]
**Describe the bug**

I can successfully start the job by running kubectl apply -f test.yaml in the command line. However, I encounter an error when creating a CRD group job using the kubernetes-client. Could you help me troubleshoot the issue? i use volcano.sh crd

**Client Version**

Client Version: v1.28.2

**Server Version**

Server Version: v1.27.4

**To Reproduce**

![image](https://github.com/kubernetes-client/javascript/assets/24582204/a6b669a1-59a2-4d19-85fd-926b6bff3fc1)

**Expected behavior**
when i use this createPod will get error

```
{
  apiVersion: 'batch.volcano.sh/v1alpha1',
  kind: 'job',
  metadata: { name: 'test-mpi-job' },
  spec: {
    minAvailable: 4,
    schedulerName: 'volcano',
    plugins: { ssh: [], svc: [] },
    tasks: [ [Object], [Object] ]
  }
}
{
  kind: 'Status',
  apiVersion: 'v1',
  metadata: {},
  status: 'Failure',
  message: 'job in version "v1alpha1" cannot be handled as a Pod: no kind "job" is registered for version "batch.volcano.sh/v1alpha1" in scheme "pkg/api/legacyscheme/scheme.go:30"',
  reason: 'BadRequest',
  code: 400
}


```

**Example Code**
```javascript
import {CoreV1Api, AppsV1Api, KubeConfig} from '@kubernetes/client-node';
import {yaml2Json} from '/@/utils';

/**
 * This class represents a Kubernetes Client for interacting with Kubernetes clusters.
 */
export class K8SClient {
  public k8sCoreApi: CoreV1Api;
  public k8sAppsApi: AppsV1Api;

  /**
   * Constructs a new instance of the class.
   *
   * @param {string} configPath - The path to the configuration file.
   */
  constructor(configPath: string) {
    // load k8s config
    const kc = new KubeConfig();
    kc.loadFromFile(configPath);
    // get k8s api version
    this.k8sCoreApi = kc.makeApiClient(CoreV1Api);
    this.k8sAppsApi = kc.makeApiClient(AppsV1Api);
  }

  /**
   * List all pods corresponding to the specified namespace.
   *
   * @param {string} name - The name of the namespace (default is 'default' if not provided).
   * @returns {Promise<Object>} A promise that resolves to the list of pods in the namespace.
   */
  public listAllPods = (name = 'default') => {
    return this.k8sCoreApi.listNamespacedPod(name);
  };

  /**
   * Create a new namespace with the provided metadata.
   *
   * @param {Object} name - The metadata for the new namespace (e.g., { metadata: { name: 'my-namespace' } }).
   * @returns {Promise<Object>} A promise that resolves when the namespace is created.
   */
  public createNamespace = (name: {metadata: {name: string}}) => {
    // TODO :  add check metadata name and arguments
    return this.k8sCoreApi.createNamespace(name);
  };

  /**
   * Delete a namespace by name.
   *
   * @param {string} name - The name of the namespace to delete.
   * @returns {Promise<Object>} A promise that resolves when the namespace is deleted.
   */
  public deleteNamespace = (name: string) => {
    return this.k8sCoreApi.deleteNamespace(name);
  };

  /**
   * Read a namespace by name.
   *
   * @param {string} name - The name of the namespace to read.
   * @returns {Promise<Object>} A promise that resolves to the namespace details.
   */
  public readNamespace = (name: string) => {
    return this.k8sCoreApi.readNamespace(name);
  };

  /**
   * Create a new pod in the specified namespace using the provided YAML file.
   *
   * @param {string} filePath - The path to the YAML file describing the pod.
   * @param {string} name - The name of the namespace (default is 'default' if not provided).
   * @returns {Promise<Object>} A promise that resolves when the pod is created.
   */
  public createPod = (filePath: string, name = 'default') => {
    const pod = yaml2Json(filePath);
    console.log(pod);
    // todo crd job
    return this.k8sCoreApi.createNamespacedPod(name, pod);
  };

}
```
other api it's work,just createPod

this is test.yaml
```yaml
apiVersion: batch.volcano.sh/v1alpha1
kind: job
metadata:
  name: test-mpi-job
spec:
  minAvailable: 4
  schedulerName: volcano
  plugins:
    ssh: []
    svc: []
  tasks:
    - replicas: 1
      name: mpimaster
      policies:
        - event: TaskCompleted
          action: CompleteJob
      template:
        spec:
          containers:
            - command:
                - /bin/sh
                - -c
                - |
                  MPI_HOST=`cat /etc/volcano/mpiworker.host | tr "\n" ","`;
                  mkdir -p /var/run/sshd; /usr/sbin/sshd;
                  mpiexec --allow-run-as-root --host ${MPI_HOST} -np 4 mpi_hello_world;
              image: volcanosh/example-mpi:0.0.3
              name: mpimaster
              ports:
                - containerPort: 22
                  name: mpijob-port
              workingDir: /home
          restartPolicy: OnFailure
    - replicas: 3
      name: mpiworker
      template:
        spec:
          containers:
            - command:
                - /bin/sh
                - -c
                - |
                  mkdir -p /var/run/sshd; /usr/sbin/sshd -D;
              image: volcanosh/example-mpi:0.0.3
              name: mpiworker
              ports:
                - containerPort: 22
                  name: mpijob-port
              workingDir: /home
          restartPolicy: OnFailure

```

**Environment (please complete the following information):**
 - OS: linux
 - NodeJS Version 18.17
 - Cloud runtime minikube 1.13.2

**Additional context**
