### ISSUE TITLE
self signed certificate in certificate chain error in 1.0.0-rc4

### ISSUE THREAD

**Issue by rudyflores** [kubernetes-client/javascript#1509]
**Describe the bug**

I receive the following error:

```BASH
request to https://example?pretty=true failed, reason: self signed certificate in certificate chain
```

this was not appearing on previous versions of the kubernetes client, I also noticed it on `0.20.0` but had to upgrade due to vulnerability issues with `request`, is there a way to get rid of this error? I am logging into my cluster and generating a token just fine which used to work.

** Client Version **
e.g. `0.12.0`

v1.0.0-rc4

** Server Version **
e.g. `1.19.1`

v1.26.6

**To Reproduce**

run any request with kubernetes client, e.g: 

```javascript
await this.kc.readNamespace({
          name: this.kubeConfig.namespace,
          pretty: "true",
});
```

**Expected behavior**

I should be able to make calls without errors about self-signed certs in cert chain.

** Example Code**
Code snippet for what you are doing

**Environment (please complete the following information):**
 - OS: [e.g. Windows, Linux] MacOS
 - NodeJS Version [eg. 10]  v18.19.0
 - Cloud runtime [e.g. Azure Functions, Lambda]

**Additional context**

**Comment by brendandburns** [comment]
There is a similar error here:

https://github.com/kubernetes-client/javascript/issues/1451

which appears to be related to the runtime environment.

**Comment by rudyflores** [comment]
@brendandburns do you know if maybe my token in my kube config is not being attached with the kubernetes client?

I tried the same request I am trying with the API call of `readNamespace()` on Postman and the request seems to work just fine there.

**Comment by brendandburns** [comment]
The switch to v1.0.4 includes a switch to a different underlying HTTP client. (fetch vs request) it's possible that's different, but it seems to work for other people.

What is the kubernetes distro that you are using? Can you send the contents of your `kubeconfig` file with any secrets redacted?

**Comment by rudyflores** [comment]
> The switch to v1.0.4 includes a switch to a different underlying HTTP client. (fetch vs request) it's possible that's different, but it seems to work for other people.
> 
> What is the kubernetes distro that you are using? Can you send the contents of your `kubeconfig` file with any secrets redacted?

Take in mind I also am seeing this issue with `v0.20.0` (Which still uses request), where as `v0.18.1` does not seem to have this issue.

The Kubernetes distro is Openshift, and this is the kubeconfig (with secrets redacted):

```yaml
apiVersion: v1
clusters:
- cluster:
    insecure-skip-tls-verify: true
    server: https://<myserver>:<myport>
  name: <myserver>:<myport>
contexts:
- context:
    cluster: <myserver>:<myport>
    namespace: <namespace>
    user: <user>/<server>:<myport>
  name: default/<myserver>:<myport>/<user>
current-context: default/<myserver>:<myport>/<user>
kind: Config
preferences: {}
users:
- name: <myuser>/<myserver>:<myport>
  user:
    token: <token>
```
