### ISSUE TITLE
access-token does not get generated if no access-token is present

### ISSUE THREAD

**Issue by macrozone** [kubernetes-client/javascript#178]
follow up of https://github.com/kubernetes-client/javascript/issues/177

If you never used an auth-provider, your .kube/config looks like this (e.g. with google cloud):

```
# ...
users:
- name: xxxclustername
  user:
    auth-provider:
      config:
        cmd-args: config config-helper --format=json
        cmd-path: /Applications/google-cloud-sdk/bin/gcloud
        expiry-key: '{.credential.token_expiry}'
        token-key: '{.credential.access_token}'
      name: gcp
```

in this case the js-client sees that there is an auth-provider and tries to get the propery `access-token`, which is undefined here.

There is some logic to update the access token if it is expired, but this also only works if the token has been generated before, because both `access-token` and `expiry` are only set on token renewal.

Additionaly, the current token renewal implementation does not store back access-token and expiry into the config.

As a reference, the `kubectl` cli behaves correctly. If there is no access-token or if it is expired, it will fetch a new one and write it back to .kube/config
