### ISSUE TITLE
Authentification

### ISSUE THREAD

**Issue by CorentinDy** [kubernetes-client/javascript#216]
Hi , 
I'm wondering if there is any way to make an authentification ? or if the error is related to something else ? 

`'pods is forbidden: User "system:anonymous" cannot list pods in the namespace "default"',`

I was trying the exemple to get pods from default namespace but I'm stuck with this error

The kubernetes cluster is on AWS.

**Comment by orojina** [comment]
The same here I'm getting:

`body:                                                                                                                                                                                                                                                                            { kind: 'Status',                                                                                                                                                                                                                                                                 apiVersion: 'v1',                                                                                                                                                                                                                                                               metadata: {},                                                                                                                                                                                                                                                                   status: 'Failure',                                                                                                                                                                                                                                                              message: 'pods is forbidden: User "system:anonymous" cannot list pods in the namespace ',                                                                                                                                                                             reason: 'Forbidden',                                                                                                                                                                                                                                                            details: { kind: 'pods' },                                                                                                                                                                                                                                                      code: 403 } }`
--

**Comment by orojina** [comment]
BTW the example to get pods from the python library works well but the nodejs is throwing the error I mentioned. I used the same config file for both runs

**Comment by brendandburns** [comment]
Can you send an example of your config file (with personal data removed, of course)

**Comment by orojina** [comment]
The config file looks similar to this:

```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: ***********
    server: https://***********.us-east-1.eks.amazonaws.com
  name: arn:aws:eks:us-east-1:***********:cluster/***********
contexts:
- context:
    cluster: arn:aws:eks:us-east-1:***********:cluster/***********
    user: arn:aws:eks:us-east-1:***********:cluster/***********
  name: arn:aws:eks:us-east-1:***********:cluster/***********
current-context: arn:aws:eks:us-east-1:***********:cluster/***********
kind: Config
preferences: {}
users:
- name: arn:aws:eks:us-east-1:***********:cluster/***********
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      args:
      - token
      - -i
      - ***********
      command: aws-iam-authenticator.exe
      env: null
```

**Comment by brendandburns** [comment]
Ah! I see the problem...

Basically it expects an `authConfig` to be present, but that's not how this is modelled (which is a little messed up imho, but oh well)

I will send a PR to fix this, in the meantime if you add:
```yaml
.....
   user:
     authConfig:
        config: {}
     exec:
        ....
```

It will work (that's a definite work-around)

The relative bug is this line here:

https://github.com/kubernetes-client/javascript/blob/master/src/config.ts#L279

**Comment by orojina** [comment]
Hi @brendandburns I tried to apply the workaround so my config file now looks like this:

```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: ***********
    server: https://***********.us-east-1.eks.amazonaws.com
  name: arn:aws:eks:us-east-1:***********:cluster/***********
contexts:
- context:
    cluster: arn:aws:eks:us-east-1:***********:cluster/***********
    user: arn:aws:eks:us-east-1:***********:cluster/***********
  name: arn:aws:eks:us-east-1:***********:cluster/***********
current-context: arn:aws:eks:us-east-1:***********:cluster/***********
kind: Config
preferences: {}
users:
- name: arn:aws:eks:us-east-1:***********:cluster/***********
  user:
    authConfig:
      config: {}
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      args:
      - token
      - -i
      - ***********
      command: aws-iam-authenticator.exe
      env: null
```

But I'm still getting the same error. 

@CorentinDy you had any luck ?
