### ISSUE TITLE
aws-iam-authenticator not found when kube config contains exec env variables

### ISSUE THREAD

**Issue by michaelgeorgeattard** [kubernetes-client/javascript#243]
I am getting an `aws-iam-authenticator not found` error with the following kube config snippet:

```
users:
- name: arn:aws:eks:eu-west-1:111111111111:cluster/foo
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      args:
      - token
      - -i
      - foo
      command: aws-iam-authenticator
      env:
      - name: AWS_PROFILE
        value: bar
```

Looks like this is due to a bug in `exec_auth.ts`:

https://github.com/kubernetes-client/javascript/blob/e5ec9456cf8cde7da768701092adf7a91583f1c9/src/exec_auth.ts#L60

`shelljs.exec` second parameter is defined below:

https://github.com/shelljs/shelljs#execcommand--options--callback

Maybe this could be solved using something like:

```
exec.env.forEach((elt) => {
  shell.env[elt.name] = elt.value;
});
```

**Comment by brendandburns** [comment]
The environment variable setup here:

https://github.com/kubernetes-client/javascript/blob/master/src/exec_auth.ts#L58

Can you add more details about the bug?

Thanks!

**Comment by brendandburns** [comment]
And I think that the error indicates that the `aws-iam-authenticator` is not in your `${PATH}`

**Comment by michaelgeorgeattard** [comment]
The bug is probably in the way `shell.exec` is called.

Transforming the below:
```
const result = shell.exec(cmd, opts); 
```

Into:
```
const result = shell.exec(cmd);
```

Allows `shelljs` to "find" `aws-iam-authenticator`.

Environment variables should NOT be passed as the second variable to `shell.exec` but rather as below:

https://github.com/shelljs/shelljs#execcommand--options--callback

**Comment by michaelgeorgeattard** [comment]
Also to replicate add `env` variables to kube config as below:

```
users:
- name: arn:aws:eks:eu-west-1:111111111111:cluster/foo
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      args:
      - token
      - -i
      - foo
      command: aws-iam-authenticator
      env:
      - name: foo
        value: bar
```
