### ISSUE TITLE
Client prints credentials on console

### ISSUE THREAD

**Issue by foxylion** [kubernetes-client/javascript#251]
We are using the `aws-iam-authenticator` to retrieve credentials for the Kubernetes cluster.

The Javascript client seems to print the generated credentials to the console. This results in a cluttered console output mixed up with normal outputs.

```
{"kind":"ExecCredential","apiVersion":"client.authentication.k8s.io/v1alpha1","spec":{},"status":{"expirationTimestamp":"2019-05-29T14:49:13Z","token":"..."}}
...my output...
{"kind":"ExecCredential","apiVersion":"client.authentication.k8s.io/v1alpha1","spec":{},"status":{"expirationTimestamp":"2019-05-29T14:49:13Z","token":"..."}}
...more of my output...
```

Is there a possibility to disable the output of credentials on the console?

My Kubernetes configuration looks like this:
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: ****
    server: https://api.k8s.mycompany.tld
  name: k8s.mycompany.tld
contexts:
- context:
    cluster: k8s.mycompany.tld
    user: k8s.mycompany.tld
  name: k8s.mycompany.tld
current-context: k8s.mycompany.tld
kind: Config
preferences: {}
users:
- name: k8s.mycompany.tld
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1alpha1
      command: aws-iam-authenticator
      args:
        - "token"
        - "-i"
        - "k8s.mycompany.tld"
        - "-r"
        - "arn:aws:iam::*****:role/KubernetesAdmin"

```
