### ISSUE TITLE
Inconsistency with go-client Azure auth

### ISSUE THREAD

**Issue by jnummelin** [kubernetes-client/javascript#358]
Not sure yet if this is a bug or not, hopefully someone more familiar with AKS might be able to help me sort that part out. :)

One of our users reported that token refresh on AKS cluster does not work. The kubeconfig for the problematic cluster is:
```
apiVersion: v1
kind: Config
preferences: {}
current-context: my-context
clusters:
  - name: my-cluster
    cluster:
      certificate-authority-data: >-
        <base 64 encoded certificate data>
      server: 'https://some-id.hcp.eastus.azmk8s.io:443'
      insecure-skip-tls-verify: false
contexts:
  - name: my-context
    context:
      cluster: my-context
      user: some-user
      namespace: app
users:
  - name: some-user
    user:
      auth-provider:
        config:
          access-token: >-
            <JWT access token>
          apiserver-id: <uuid>
          client-id: <uuid>
          environment: AzurePublicCloud
          expires-in: '3600'
          expires-on: '1571778882'
          refresh-token: >-
            <refresh token>
          tenant-id: <uuid>
        name: azure
```

Looking at the Azure auth [here](https://github.com/kubernetes-client/javascript/blob/master/src/cloud_auth.ts) makes me think this sort of auth is not really supported at all. To me it looks like this is some sort of AKS / Azure AD auth integration. All my limited trials with AKS has been using cert authentication so haven't really stumbled anything like this before.

Then looking at the go-client auth for Azure [here](https://github.com/kubernetes/client-go/blob/dbd11fce0f2e8da137f09b53d8a59cecc8e85dc8/plugin/pkg/client/auth/azure/azure.go) it seems like it is able to use this sort of auth config.

So this raises up two questions:
1. Should this sort of auth config even work currently? If not, is there any workarounds we could do for short term?
2. Why is the JS client Azure auth so totally different from go-client counterpart? Or am I looking at wrong pieces of code?

Then the bigger question/topic: As there's gazillion different permutations how auth can be configured in Kubeconfig and all the different libraries in different languages seem to be playing catch-up with each other on those, has there been any discussion of building _something_ that could be generally usable for all?
