### ISSUE TITLE
informer triggers update event indefinitely

### ISSUE THREAD

**Issue by riker09** [kubernetes-client/javascript#379]
I want to use the informer to watch services and perform my custom logic. Here's my code:

```typescript
import * as k8s from '@kubernetes/client-node';

const kc = new k8s.KubeConfig();
kc.loadFromDefault();

this._k8sApi = kc.makeApiClient(k8s.CoreV1Api);

// Get all services
const svcs = await this._k8sApi.listNamespacedService('default');

// Filter by annotation "my-annotation"
const svcNames = svcs.body.items
    .filter(svc => svc.metadata.annotations && svc.metadata.annotations.hasOwnProperty('my-annotation'))
    .map(svc => svc.metadata.labels['my-annotation']);

const listFn = () => this._k8sApi.listNamespacedService('default', null, false, null, null, `my-annotation in (${svcNames.join(',')})`);

const informer = k8s.makeInformer(kc, svcs.body.metadata.selfLink, listFn);

informer.on('update', (obj: k8s.V1Service) => { console.log(`Updated: ${obj.metadata!.name}`); });
```

I only want to watch services annotated with a custom string `my-annotation`. I get *ALL* services first and compile a list with the names (`svcNames`). This normally runs inside an `async` method, hence the `await` keyword. I then use that list in a second call to `listNamespacedServices` (see `const listFn = () => ...`.
When running this the `update` event is called over and over with the same objects (as far as I can tell). I tried reading the Kubernetes API and get an understanding but quite frankly, I'm overwhelmed. I was wondering if this is intentional behaviour? How many update events are there for a typical service? Any help will be greatly appreciated.

**Comment by brendandburns** [comment]
Depends on what is going on in the cluster.

There are two possibilities:

1) The Watch is dropping. You'll get a new event every time the watch re-connects.

2) The object really is changing a lot. You can check the `resourceVersion` field in the object. If that version is changing, then the object really is changing a lot.

Or it's possible there's a bug. If the watch isn't dropping and the object isn't changing, please supply more details and we'll see if there is a bug somewhere.

**Comment by riker09** [comment]
The objects are not changing. I've logged the resource version and it stays the same for each object (service). I've also encountered this behaviour with pod resources.

How can I tell if the watch is dropping? If this was the case, shouldn't the other events trigger as well? I have listeners for `add` and `delete` as well, but only `update` displays this behaviour.

Please let me know what more details I should provide (and how to do so). Full disclosure: I'm fairly new to Kubernetes and it is quite possible that there is something misconfigured in my cluster. I'm using K3S and I deploy with Helm.

```bash
$ kubectl version
Client Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3-k3s.2", GitCommit:"e7e6a3c4e9a7d80b87793612730d10a863a25980", GitTreeState:"clean", BuildDate:"2019-11-18T18:31:23Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}
Server Version: version.Info{Major:"1", Minor:"16", GitVersion:"v1.16.3-k3s.2", GitCommit:"e7e6a3c4e9a7d80b87793612730d10a863a25980", GitTreeState:"clean", BuildDate:"2019-11-18T18:31:23Z", GoVersion:"go1.13.4", Compiler:"gc", Platform:"linux/amd64"}

$ helm version
Client: &version.Version{SemVer:"v2.16.1", GitCommit:"bbdfe5e7803a12bbdf97e94cd847859890cf4050", GitTreeState:"clean"}
Server: &version.Version{SemVer:"v2.16.1", GitCommit:"bbdfe5e7803a12bbdf97e94cd847859890cf4050", GitTreeState:"clean"}
```
I have some services that are "attached" to pods which are currently crashing and are stuck in a CrashLoopBackOff. But some are not and the `update` event is repeatedly triggered for all of them.

**Comment by brendandburns** [comment]
To see if the watches are dropping you'd have to instrument the code, or look at your API server to see if there are repeated calls to list and/or re-establish the watch call.

Note also that this library has only been tested with vanila open source Kubernetes, not `k3s` so it's also possible that's part of the problem.

**Comment by wdalmut** [comment]
Hi finally ended in the same problem. And i found that the function `listFn` is continuously called. Here an example

```
const k8s = require('@kubernetes/client-node');

const kc = new k8s.KubeConfig();
kc.loadFromDefault();

const k8sApi = kc.makeApiClient(k8s.CustomObjectsApi);

const informer = k8s.makeInformer(kc, '/apis/app.corley.it/v1', () => {
  // *******************************************************
  console.log("CALL")  // PRINT OUT WHEN IS CALLED!!!!!!!  *
  //********************************************************
  return k8sApi.listClusterCustomObject('app.corley.it', 'v1', 'conferences')
})

informer.on('add', (obj) => console.log("add", obj))
informer.on('update', (obj) => console.log("update", obj))
informer.on('delete', (obj) => console.log("delete", obj))

informer.start()
```

If you run this snippet your will see in your console

```js
CALL
CALL
CALL
...
```

If you use the `informer.ts` example you will only get the `CALL` log once.

It is possible a bug? I don't undestand how to solve that.

To complete my report i attach a custom resource definition for the cluster

```yaml
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: conferences.app.corley.it
spec:
  group: app.corley.it
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                title:
                  type: string
                description:
                  type: string
                on_day:
                  type: string
      additionalPrinterColumns:
      - name: Title
        type: string
        description: The conference title
        jsonPath: .spec.title
  scope: Cluster
  names:
    plural: conferences
    singular: conference
    kind: Conference
    shortNames:
    - conf
``` 

And a testing `Conference` object

```js
apiVersion: "app.corley.it/v1"
kind: Conference
metadata:
  name: example1
spec:
  title: "Example Conference"
  description: "Example description for conference 1"
  on_day: "2020-03-19"
```
