### ISSUE TITLE
Log class seems to be outdated

### ISSUE THREAD

**Issue by inikolaev** [kubernetes-client/javascript#405]
I'm trying to stream logs from the pod using `Log` class and I'm getting an unauthenticated error:

```json
{"kind":"Status","apiVersion":"v1","metadata":{},"status":"Failure","message":"Unauthorized","reason":"Unauthorized","code":401}
```

At the same time both `kubectl logs` and `readNamespacedPodLog` works.

I guess the problem is that `Log` uses

```js
this.config.applyToRequest(requestOptions);
```

while `readNamespacedPodLog` uses

```js
let authenticationPromise = Promise.resolve();
authenticationPromise = authenticationPromise.then(() => this.authentications.BearerToken.applyToRequest(localVarRequestOptions));
authenticationPromise = authenticationPromise.then(() => this.authentications.default.applyToRequest(localVarRequestOptions));
```

in order to apply proper credentials.

That makes me wonder if `Log` class still a thing and I can rely on it, or should I fallback on `readNamespacedPodLog`, though I'm not clear whether I can use `follow` with it and how.

EDIT: I guess I can `pipe` the response in a similar way it's done in the `Log` class:

```js
api.readNamespacedPodLog(pod, namespace, container, )
  .then((response) => {
    response.response.pipe(writable);
  });

**Comment by brendandburns** [comment]
acknowledged, will try to reproduce and fix.

**Comment by brendandburns** [comment]
Actually, I tried this on my cluster and it works correctly. What kind of authentication are you using in your kubeconfig?

The code paths actually end up with the same Authentication since `this.authentications.default.applyToRequest(...)` ultimately calls `config.applyToRequest` since the config is passed in as the default authencation.

Anyway, I suspect that some part of your kubeconfig is being mis-handled by the library, so seeing the kubeconfig (secrets removed of course) will help understand where the error is.

**Comment by inikolaev** [comment]
I have just tried and still getting unauthorized. It Dows work when I run it agains Kubernetes which runs inside my Docker for Desktop, which doesn't require authentication. 

Here's an example source code which I used:

```ts
const done = (error: any) => {
    console.error('Stream is DONE', error);
};

const options = {
    follow: true,
    tailLines: 100
} as LogOptions

const log = new Log(config);
log.log(namespace, pod, container, stream, done, options);
```

The `readNamespacedPodLog` only works for me if `follow` is `undefined` of `false`, so I guess it's not quire suitable for streaming after all or I'm using it in a wrong way. Here's what I tried:

```ts
const stream = new Writable({
    write(chunk, encoding, callback) {
        console.log(chunk);
        callback();
    }
});

api.readNamespacedPodLog(pod, namespace, container, true, undefined, undefined, undefined, undefined, 100)
    .then((response) => {
        // This is never being called
        console.log('Response handler');
        console.log(response.body);
        response.response.pipe(stream);
    })
    .catch((e) => console.log(e));
```

As for my kubeconfig here's what it looks like:

```yaml
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: 
    server: 
  name: dev
- cluster:
    certificate-authority-data: 
    server: 
  name: docker-desktop
- cluster:
    certificate-authority-data: 
    server: 
  name: prod
- cluster:
    insecure-skip-tls-verify: true
    server: 
  name: testing
contexts:
- context:
    cluster: dev
    namespace: dev
    user: dev
  name: dev
- context:
    cluster: docker-desktop
    user: docker-desktop
  name: docker-desktop
- context:
    cluster: docker-desktop
    user: docker-desktop
  name: docker-for-desktop
- context:
    cluster: prod
    namespace: prod
    user: prod
  name: prod
- context:
    cluster: testing
    namespace: testing
    user: testing
  name: testing
current-context: dev
kind: Config
preferences: {}
users:
- name: docker-desktop
  user:
    client-certificate-data: 
    client-key-data: 
- name: dev
  user:
    auth-provider:
      config:
        client-id: kubernetes
        client-secret: 
        id-token: 
        idp-issuer-url: 
        refresh-token: 
      name: oidc
- name: prod
  user:
    auth-provider:
      config:
        client-id: kubernetes
        client-secret: 
        id-token: 
        idp-issuer-url: 
        refresh-token: 
      name: oidc
- name: testing
  user:
    auth-provider:
      config:
        client-id: kubernetes
        client-secret: 
        id-token: 
        idp-issuer-url: 
        refresh-token: 
      name: oidc
```

Let me know if I can do anything else in order to help with troubleshooting.
