### ISSUE TITLE
Support SPDY for exec

### ISSUE THREAD

**Issue by inikolaev** [kubernetes-client/javascript#411]
I have cluster in with I could exec into a pod using `Exec` class, but recently it stopped working and now return `403` status code when doing so. 

At the same time `kubectl exec` works fine and after some digging it looks like there are two protocols which can be used: WebSocket and SPDY. SPDY is used by `kubectl` and that is why it's still working.

**Comment by brendandburns** [comment]
An HTTP 403 comes before any protocol (SPDY or WebSockets) is negotiated. So I don't think SPDY vs WebSockets is the reason that you are getting a 403.

My guess is that your kubeconfig is somehow incompatible with the Java. What is the content of your kubeconfig (after removing secrets)

**Comment by inikolaev** [comment]
Unfortunately I don't have access to the kubeconfig, but I can ask about it.

The thing is that it was working before and looks like something changed. As I understand WebSocket and SPDY protocol negotiation is started differently: WebSocket requires that the first request is GET, while `kubectl` is sending POST which is then upgraded. Could it be that the corresponding role in Kubernetes for `pod/exec` only allows POST requests and not GET?

I managed to find different issues which look similar to me, but I'm not well versed in K8s internals:

- https://github.com/kubernetes/kubernetes/issues/78741
- https://github.com/kubernetes-client/python/issues/690
- https://github.com/godaddy/kubernetes-client/issues/346

By the way I got confused by these two methods: `connectPostNamespacedPodExec` and `connectGetNamespacedPodExec`. What are they supposed to be used for?

**Comment by inikolaev** [comment]
Here's an example kubeconfig:

```yaml
apiVersion: v1
clusters:
- cluster:
    server: https://cluster1
  name: cluster1
- cluster:
    server: https://cluster2
  name: cluster2
contexts:
- context:
    cluster: cluster1
    namespace: namespace1
    user: username
  name: cluster1
- context:
    cluster: cluster2
    namespace: namespace2
    user: username
  name: cluster2
current-context: cluster1
kind: Config
preferences: {}
users:
- name: username
  user:
    token: some token here
```

and here's extract from Kubernetes roles:

```yaml
- apiGroups:
  - ""
  resources:
  - pods
  - pods/attach
  - pods/eviction
  - pods/exec
  verbs:
  - create
  - delete
  - deletecollection
  - patch
  - update
```
