### ISSUE TITLE
auth with access token instead of username and password

### ISSUE THREAD

**Issue by frederik-b** [kubernetes-client/javascript#42]
Hi there,

I'm trying to use this on the OTC (open telecom cloud).

They provide a forked version for kubectl here:
https://github.com/Cusfomer-kubectl/kubernetes

And in the end I have a kube config file that looks like this:
```
apiVersion: v1
clusters:
- cluster:
    cluster-uuid: 4f65a35c-a9c8-4c98-87a4-xxxxxxxxxxxx
    server: https://cce.eu-de.otc.t-systems.com
  name: fg-dev
contexts:
- context:
    cluster: fg-dev
    user: frederik_berg
  name: fg-dev
current-context: fg-dev
kind: Config
preferences: {}
users:
- name: frederik_berg
  user:
    access-key: <access-key consisting of uppercase alphanum chars>
    region-id: eu-de
    secret-key: <secret-key consisting of mixed case alphanum chars>
```

the config_types.js looks like it dosn't support this:
```
function userIterator() {
    return function (elt, i, list) {
        if (!elt.name) {
            throw new Error(`users[${i}].name is missing`);
        }
        let token = null;
        if (elt.user["token"]) {
            token = elt.user["token"];
        }
        if (elt.user["token-file"]) {
            token = fs.readFileSync(elt.user["token-file"]);
        }
        return {
            name: elt.name,
            certData: elt.user["client-certificate-data"],
            certFile: elt.user["client-certificate"],
            keyData: elt.user["client-key-data"],
            keyFile: elt.user["client-key"],
            authProvider: elt.user["auth-provider"],
            token: token,
        };
    };
}
```

Is there any way I can make this work?

P.S. this is using the newest version available from npm/yarn not from git directly
