### ISSUE TITLE
Possible typing mistake in class `V1HTTPGetAction`

### ISSUE THREAD

**Issue by rivernews** [kubernetes-client/javascript#444]
The typing of `port` seems to be incorrect:

```ts
export declare class V1HTTPGetAction {

  ...

  /**
     * Name or number of the port to access on the container. Number must be in the range 1 to 65535. 
  Name must be an IANA_SVC_NAME.
   */
  'port': object;

  ...

```

As you can see, the `port` type is `object`. However, the comments in the class is indicating it should be a Name or number.

When I look at the [Kubernetes documentation](https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/#define-startup-probes), it seems that `port` are provided by either a string or a number:
```
livenessProbe:
  httpGet:
    path: /healthz
    port: liveness-port   <--- either a string indicating port name, or a number for the port
```

I'm wondering should `port` be type of `number | string` instead? Or let me know if I'm missing anything else. If somebody else can confirm this understanding is correct, I can create a PR for this.

** I'm using the latest version `0.11.2`.
