### ISSUE TITLE
Using with GKE

### ISSUE THREAD

**Issue by Olympuus** [kubernetes-client/javascript#448]
I've successful created a little test to create a pod in the default namespace, locally it works fine, it creates the pod. But when i test it in a GKE cluster i receive "HttpError: HTTP request failed".

Here is my code:
```
const k8s     = require("@kubernetes/client-node");

const kc = new k8s.KubeConfig();
kc.loadFromDefault();

const k8sApi = kc.makeApiClient(k8s.CoreV1Api);

var pod = {
            metadata: {
                name: "name"
            },
            spec: {
                containers: [
                    {
                        image: "image",
                        name: "name"
                    },
                ],
            },
        };

k8sApi.createNamespacedPod("default", pod).then(
    (response) => {
        console.log("Created pod -> ${response}");
    },
    (err) => {
        console.log("Error: ${err}");
    }
);
```

**Comment by brendandburns** [comment]
We need more details to debug. Does kubectl work in the same environment? are there more details in the error object? What is the content of your $HOME/.kube/config file?

**Comment by Olympuus** [comment]
Yes, kubectl works in the same enviroment and that error information is the only thing i get. Here is the contents of $HOME/.kube/config:

```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: certificate
    server: https://35.205.83.11
  name: gke_leafy-analyst-274717_europe-west1-b_backend
contexts:
- context:
    cluster: gke_leafy-analyst-274717_europe-west1-b_backend
    user: gke_leafy-analyst-274717_europe-west1-b_backend
  name: gke_leafy-analyst-274717_europe-west1-b_backend
current-context: gke_leafy-analyst-274717_europe-west1-b_backend
kind: Config
preferences: {}
users:
- name: gke_leafy-analyst-274717_europe-west1-b_backend
  user:
    auth-provider:
      config:
        access-token: token
        cmd-args: config config-helper --format=json
        cmd-path: /usr/lib/google-cloud-sdk/bin/gcloud
        expiry: "2020-05-13T14:44:14Z"
        expiry-key: '{.credential.token_expiry}'
        token-key: '{.credential.access_token}'
      name: gcp
```

I deleted the certificate-authority-data and token here, because i don't know if that should be shown publicly.

**Comment by brendandburns** [comment]
Instead of `console.log(`Error: ${err}` which will call `toString()` can you log `console.log(err)` which should print the entire object. I think there are likely more details in that object like the HTTP response code.

**Comment by Olympuus** [comment]
I've figured it out, i was getting a forbidden message after doing what you told me to do, and i find out that i had to create a role inside my GKE cluster. Here is my Role and RoleBinding files that i created for testing that allows the creation of pods:

```
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: api-role
  namespace: default
  labels:
    app: tools-rbac
rules:
- apiGroups: [""]
  resources: ["pods"]
  verbs: ["create"]
```

```
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: global-rolebinding
  namespace: default
  labels:
    app: tools-rbac
subjects:
- kind: Group
  name: system:serviceaccounts
  apiGroup: rbac.authorization.k8s.io
  namespace: default
roleRef:
  kind: Role
  name: api-role
  apiGroup: ""
```
