### ISSUE TITLE
exportConfig: context has extraneous 'name'

### ISSUE THREAD

**Issue by Morriz** [kubernetes-client/javascript#451]
When `exportConfig` is used, I see this:
```yaml
contexts:
  - name: ...
    context:
      name: ...
      namespace: ...
      user: ...
      cluster: ...
```
A k8s config not also have the name in the exported context
