### ISSUE TITLE
portForward generates Unexpected server response: 401 on websocket with sample

### ISSUE THREAD

**Issue by si458** [kubernetes-client/javascript#488]
Hi All,

im trying to find out what im doing wrong or maybe its just my config/setup

the sample for the portFoward isnt working as i keep getting an error saying `Unexpected server response: 401` in the console

the error only appears when i try and connect to the localport on my laptop

however when i call the listnamespacedpod command, it returns the pods listed in that namespace so im abit confused?

my code is very simple
```
const k8s = require("@kubernetes/client-node");
const net = require("net");
const kc = new k8s.KubeConfig();
kc.loadFromDefault();
const k8sApi = kc.makeApiClient(k8s.CoreV1Api);
k8sApi.listNamespacedPod("kubenav").then((res) => {
  console.log(res.body);
});
const forward = new k8s.PortForward(kc);
const server = net.createServer((socket) => {
  forward.portForward("kubenav","kubenav-5b9bdbb9cc-b4qtd",[14122],socket,null,socket);
});
server.listen(14122, 'localhost');
```
any my kubeconfig looks like this
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: xxxxxx
    server: https://kubernetes.xxxxxx.com:6443
  name: default
contexts:
- context:
    cluster: default
    user: default
  name: default
current-context: default
kind: Config
preferences: {}
users:
- name: default
  user:
    password: xxxxxx
    username: admin
```
