### ISSUE TITLE
How to update configMap with appended data?

### ISSUE THREAD

**Issue by sonisaurabh19** [kubernetes-client/javascript#489]
hi, I am trying to update (append) configMap that consists of an array of JSON objects. Initially it is `[]` but will have the following structure:

```
[
  {
    name: string,
    age: number
  }
]
````

I use the following 3 approaches to update the configMap, 1st and 2nd don't work. The 3rd works with two issues, i) deletes old config not append, ii) Not accepting JSON object.

```
     // first
    const patchedConfigMap = {
      data: {
        "users.json": {
           name:  "sam",
           age: 10
        }
      }
    }; 

     // second
    const patchedConfigMap =   {
      data: {
        "path": "/users.json/",
        "op": "add",
        "value": {
          "name": "user-one",
          "age": 10
        }
      }
    }

     // third
    const patchedConfigMap =   {
      data: {
        "users.json": "user-one"
      }
    }


    k8sApi.patchNamespacedConfigMap('my-config-map', 'my-namespace', patchedConfigMap, undefined, undefined, undefined, undefined,
    { headers: { 'content-type': 'application/merge-patch+json' } })
```

Can I get some pointers around this?

**Comment by sonisaurabh19** [comment]
This is the configMap I am trying to update:

```
kind: ConfigMap
apiVersion: v1
metadata:
  name: my-config-map
data:
  users.json: |-
    []
```

**Comment by brendandburns** [comment]
There's a Java example of patching here:

https://github.com/kubernetes-client/java/blob/master/examples/src/main/java/io/kubernetes/client/examples/PatchExample.java

That may help.

You can also use `replace...` instead of `patch...` if you want to.

**Comment by MichielDeMey** [comment]
For anyone interested, I've managed to update the configMap using a merge patch strategy to update the data.

ConfigMap example:
```yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: 'foo'
  namespace: 'my-namespace'
data:
  somefile.json: '{}'
  state.json: '{}'
immutable: true

```


```typescript
const headers = { 'content-type': 'application/strategic-merge-patch+json' };
const { body: configMap } = await coreApi.patchNamespacedConfigMap(
 'foo',
  'my-namespace',
  {
    data: { 'state.json': JSON.stringify({ foo: 'bar' }) },
  },
  undefined,
  undefined,
  undefined,
  undefined,
  { headers },
);

return configMap;
```

Obviously, ConfigMaps can only store key/values where the value must be a string so you'll need to serialize your JSON.
