### ISSUE TITLE
Error authenticating (exec_auth) with doctl (digitalocean)

### ISSUE THREAD

**Issue by TheTFo** [kubernetes-client/javascript#496]
Hello,

The auth exec command for getting digitalocean credentials appears to fail:

```
    Error: Command failed: doctl kubernetes cluster kubeconfig exec-credential <<my-id-omitted>> --version=v1beta1 --context=<<my-context-omitted>>
    
    
        at makeError (/home/tony/repos/k8s-jest/node_modules/execa/index.js:174:9)
        at ExecAuth.module.exports.sync [as execFn] (/home/tony/repos/k8s-jest/node_modules/execa/index.js:338:15)
        at ExecAuth.getCredential (/home/tony/repos/k8s-jest/node_modules/@kubernetes/client-node/dist/exec_auth.js:81:29)
        at ExecAuth.<anonymous> (/home/tony/repos/k8s-jest/node_modules/@kubernetes/client-node/dist/exec_auth.js:24:37)
        at Generator.next (<anonymous>)
        at /home/tony/repos/k8s-jest/node_modules/@kubernetes/client-node/node_modules/tslib/tslib.js:115:75
        at new Promise (<anonymous>)
        at Object.__awaiter (/home/tony/repos/k8s-jest/node_modules/@kubernetes/client-node/node_modules/tslib/tslib.js:111:16)
        at ExecAuth.applyAuthentication (/home/tony/repos/k8s-jest/node_modules/@kubernetes/client-node/dist/exec_auth.js:23:24)
        at KubeConfig.<anonymous> (/home/tony/repos/k8s-jest/node_modules/@kubernetes/client-node/dist/config.js:328:37) {
      code: 1,
      stdout: '',
      stderr: '',
      failed: true,
      signal: null,
      cmd: 'doctl kubernetes cluster kubeconfig exec-credential <<my-id-omitted>> --version=v1beta1 --context=<<my-context-omitted>>',
      timedOut: false
    }
```
The same command works fine from my CLI, and kubectl is working correctly.  I'm not really sure how to proceed here without switching to a less optimal form of auth. Any help is appreciated to understand how I can get this to run, or dig up more info as to why the command fails.

Thanks!

**Comment by brendandburns** [comment]
This is executing that shell command, that command is failing (returning status code 1), you need to debug why it's returning a non-zero status code. I don't have a digital ocean environment so it's hard for me to debug.

First thing to do is probably to validate that the exec command is identical in both `kubectl` and this client.

If you attach the authProvider section from your kubeconfig (anonymize please!) I can see if there's anything obvious.

**Comment by TheTFo** [comment]
I ran the command manually from the CLI without issue. Are there other
steps I can take?

I'll get you the config shortly!

**Comment by brendandburns** [comment]
After you run the command, can you type `echo $?` to see what the return code from the command was?

Thanks!

**Comment by brendandburns** [comment]
e.g. run: `doctl kubernetes cluster kubeconfig exec-credential <<my-id-omitted>> --version=v1beta1 --context=<<my-context-omitted>>` (with the write values for id and context) and then run `echo $?` and report the number that it prints.

**Comment by TheTFo** [comment]
Hi Brendan,

I'll get that for you tonight, I apologize I got pulled away yesterday. I appreciate your response!

**Comment by TheTFo** [comment]
btw, I should also mention that doctl is running as a snap in Linux Mint, just an FYI

**Comment by TheTFo** [comment]
Here's the output from running the command in the CLI
```
$ doctl kubernetes cluster kubeconfig exec-credential --version=v1beta1 --context=<<my-context>> <<my-id>>
{"kind":"ExecCredential","apiVersion":"client.authentication.k8s.io/v1beta1","spec":{},"status":{"expirationTimestamp":"2020-09-16T03:51:24Z","token":<<my-token>>}}
$ echo $?
0
```

Here's the kube config:
```
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: <<my-ca-data>>
    server: https://<<my-id>>.k8s.ondigitalocean.com
  name: mycluster
contexts:
- context:
    cluster: mycluster
    user: mycluster-admin
  name: mycluster
current-context: mycluster
kind: Config
preferences: {}
users:
- name: mycluster-admin
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - kubernetes
      - cluster
      - kubeconfig
      - exec-credential
      - --version=v1beta1
      - --context=<<my-context>>
      - <<my-id>>
      command: doctl
      env: null
```
