### ISSUE TITLE
QUESTION: how to create a custom resource for already defined CRD

### ISSUE THREAD

**Issue by jobcespedes** [kubernetes-client/javascript#619]
Hi,

i've looked through the docs and examples, but haven't figure out how to create a custom resource for an already defined CRD. Any pointers on how to create the custom resource in the following yaml:
```yaml
apiVersion: m4e.krestomat.io/v1alpha1
kind: M4e
metadata:
  name: m4e-sample
spec:
  moodle_new_instance_fullname: Demo site
  moodle_new_instance_shortname: demo
  moodle_new_instance_summary: A demo site
  moodle_new_instance_adminuser: admin
  moodle_new_instance_adminpass: secret
  moodle_new_instance_adminmail: admin@example.com
  moodle_new_instance_agree_license: true
  security_context: false
```

Thanks
