### ISSUE TITLE
HTTP request failed inside a ubuntu claster - listNamespacedJob

### ISSUE THREAD

**Issue by Azbesciak** [kubernetes-client/javascript#654]
**Describe the bug**
I suppose it is not a bug, rather my lack of knowledge. I used to run this lib both in my local windows just in node js context and also inside image running in Kubernetes, and that worked fine. However, today I set up a new kubernetes cluster in raw ubuntu, and I am not able to run it - it throws an error like below:
```
/node_modules/@kubernetes/client-node/dist/gen/api/batchV1Api.js:539
                                reject(new apis_1.HttpError(response, body, response.statusCode));
                                       ^

HttpError: HTTP request failed
    at Request._callback (/node_modules/@kubernetes/client-node/dist/gen/api/batchV1Api.js:539:40)
    at Request.self.callback (/node_modules/request/request.js:185:22)
    at Request.emit (node:events:365:28)
    at Request.<anonymous> (/node_modules/request/request.js:1154:10)
    at Request.emit (node:events:365:28)
    at IncomingMessage.<anonymous> (/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (node:events:471:28)
    at IncomingMessage.emit (node:events:377:35)
    at endReadableNT (node:internal/streams/readable:1312:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21) {
... more in attached logs
```
This fails with following code:
```typescript
    const config = new KubeConfig();
    config.loadFromDefault();
    const client = config.makeApiClient(BatchV1Api);
    client.listJobForAllNamespaces().then(...);
```
this code is invoked just after my service starts - it is a scheduled task maintenance platform, it clears obsolete tasks periodically.
I would like to admit - I am not a kubernetes geek, so please advise me what to do/what I should to add. Thanks.
** Client Version **
 `1.21`

** Server Version **
`1.21`

**Environment (please complete the following information):**
 - OS: Ubuntu 18.04.5 LTS
 - NodeJS Version: docker image node:16.0.0-alpine3.13
 - Cloud runtime: Azure, but on raw Ubuntu mentioned above

**Additional context**
Log from dashboard
[logs-from-opti-api-in-task-scheduler-api-5679f99b67-mndnk.txt](https://github.com/kubernetes-client/javascript/files/6453477/logs-from-opti-api-in-task-scheduler-api-5679f99b67-mndnk.txt)

**Comment by Azbesciak** [comment]
I did as described in [the answer](https://stackoverflow.com/questions/65527852/jobs-batch-is-forbidden-user-systemserviceaccountdefaultdefault-cannot)... exactly I applied this:
```yml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: node-apis
---
kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: node-apis
rules:
  - apiGroups:
      - ""
      - "apps"
      - "batch"
    resources:
      - endpoints
      - deployments
      - pods
      - jobs
      - namespaces
      - services
    verbs:
      - get
      - list
      - watch
      - create
      - delete
---
kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: node-apis
  namespace: default
subjects:
  - kind: ServiceAccount
    name: node-apis
    namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: node-apis
```

to my `deployment`:
```yml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-scheduler-api
spec:
  selector:
    matchLabels:
      run: task-scheduler-api
  replicas: 1
  template:
    metadata:
      labels:
        run: task-scheduler-api
    spec:
      containers:
        - name: con-1
          image: xxx/xxx
          ports:
            - containerPort: 3333
          volumeMounts:
            - name: solver
              mountPath: /solver
        - name: con-2
          image: xxx/xxx
          ports:
            - containerPort: 80
      serviceAccountName: node-apis # <------- there
      imagePullSecrets:
        - name: azure-repo
      restartPolicy: Always
      volumes:
        - name: solver
          hostPath:
            path: "/home/xyz/solver"
            type: Directory
```

But it does not work...

**Comment by brendandburns** [comment]
Looking at the path, I think that your `namespace` parameter is undefined or empty. The path in your error:

`"href":"https://10.96.0.1:443/apis/batch/v1/jobs"` doesn't have a namespace in it.

**Comment by Azbesciak** [comment]
Oh, sorry. I am calling `listJobForAllNamespaces`.

**Comment by ivanstanev** [comment]
> Oh, sorry. I am calling `listJobForAllNamespaces`.

You might need ClusterRole and ClusterRoleBinding if you're trying to access resources in _all_ namespaces

**Comment by Azbesciak** [comment]
I changed `Role` and `RoleBinding` to `ClusterRole` and `ClusterRoleBinding` as below:
```yml
apiVersion: v1
kind: ServiceAccount
metadata:
  name: node-apis
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: node-apis
rules:
  - apiGroups:
      - ""
      - "apps"
      - "batch"
    resources:
      - endpoints
      - deployments
      - pods
      - jobs
      - namespaces
      - services
    verbs:
      - get
      - list
      - watch
      - create
      - delete
---
kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: node-apis
  namespace: default
subjects:
  - kind: ServiceAccount
    name: node-apis
    namespace: default
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: node-apis
```
And now all namespaces request works.
But `listNamespacedJob(namespace)` still does not work; I changed exception handler and the only message is 
```
body: {"apiVersion":"v1","kind":"Status","metadata":{}}, message: HTTP request failed +50560ms
HttpError: HTTP request failed
    at Request._callback (/node_modules/@kubernetes/client-node/dist/gen/api/coreV1Api.js:9709:40)
    at Request.self.callback (/node_modules/request/request.js:185:22)
    at Request.emit (node:events:365:28)
    at Request.<anonymous> (/node_modules/request/request.js:1154:10)
    at Request.emit (node:events:365:28)
    at IncomingMessage.<anonymous> (/node_modules/request/request.js:1076:12)
    at Object.onceWrapper (node:events:471:28)
    at IncomingMessage.emit (node:events:377:35)
    at endReadableNT (node:internal/streams/readable:1312:12)
    at processTicksAndRejections (node:internal/process/task_queues:83:21)
```
printed with this code
```typescript
`body: ${JSON.stringify(exception.body)}, message: ${exception.message}`, exception.stack
```
status is again 403.
Namespace is not important - the result is the same for any value (default or any other).
Just to remind - *outside the cluster the code works*.

Any idea?
