### ISSUE TITLE
Cannot patch Istio Custom Resources using `CustomObjectAPI`

### ISSUE THREAD

**Issue by vyrwu** [kubernetes-client/javascript#656]
**Describe the bug**
Cannot patch Istio Custom Resources using `CustomObjectAPI`. I've also experienced issues creating new resources from YAML specs and replacing them using provided API namespaced commands. 

** Client Version **
e.g. `0.14.3`

** Server Version **
e.g. `v1.17.12-eks`

**To Reproduce**
See edits in this [stackoverflow issue](https://stackoverflow.com/questions/67520468/patch-k8s-custom-resource-with-kubernetes-client-node).

**Expected behavior**
It should work as expected, or if I am missing something, it should give clear hints in the documentation.

** Example Code**
When using CustomObjectApi.patchNamespacedCustomObject function, I'm getting the following error back from K8s API:

`message: 'the body of the request was in an unknown format - accepted media types include: application/json-patch+json, application/merge-patch+json, application/apply-patch+yaml', reason: 'UnsupportedMediaType', code: 415`

My Code:
```js
const k8sYamls = `${path.resolve(path.dirname(__filename), '..')}/k8sYamls`
const vServiceSpec = read(`${k8sYamls}/${service}/virtual-service.yaml`)
const kc = new k8s.KubeConfig()
kc.loadFromDefault()
const client = kc.makeApiClient(k8s.CustomObjectsApi)
const result = await client.patchNamespacedCustomObject(
  vServiceSpec.apiVersion.split('/')[0],
  vServiceSpec.apiVersion.split('/')[1],
  namespace,
  'virtualservices',
  vServiceSpec.metadata.name,
  vServiceSpec
)
```
virtual-service.yaml:
```yaml
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: message-service
spec:
  hosts:
  - message-service
  http:
  - name: 'production'
    route:
    - destination:
        host: message-service
      weight: 100
    retries:
      attempts: 3
      perTryTimeout: 2s
      retryOn: 5xx
```

**Environment (please complete the following information):**
 - OS: macOS Big Sur 11.2.3
 - NodeJS Version 14.13.0

**Additional context**
```bash
❯ istioctl version        
client version: 1.9.2
control plane version: 1.9.2
data plane version: 1.9.2 (23 proxies)
```
