### ISSUE TITLE
Unable to connect to the server: x509: certificate signed by unknown authority

### ISSUE THREAD

**Issue by mansona** [kubernetes-client/javascript#691]
**Describe the bug**
I'm trying to use this client to connect to kubernetes in Google Cloud (GKE) and I am having some trouble getting it to work with node 🤔 I have managed to successfully connect using `kubectl` on the command line with the correct `KUBECONFIG` env variable exported but it doesn't seem to be working from the node client and I don't really know how to debug this any further 🙃 

**Client Version**
specified: "@kubernetes/client-node": "^0.15.0",
resolved (in package-lock): "version": "0.15.0",

**Server Version**
1.19.10

**To Reproduce**
I have a GKE cluster and have followed these instructions for authentication: https://cloud.google.com/kubernetes-engine/docs/how-to/api-server-authentication#service_in_other_environments

**Expected behavior**
As I said, this works with `kubectl` on the same machine, I am able to describe the cluster and get pods. I originally had the same error on command line because I'm using the node **slim** docker containers and I needed on install ca-certificates but once I did this the command line `kubectl` started working without any issue.

**Example Code**
I'm not doing anything wild and wonderful, here is the function that I'm calling that is actually failing: 

```javascript
const k8s = require('@kubernetes/client-node');

const kc = new k8s.KubeConfig();

kc.loadFromDefault();

const k8sApi = kc.makeApiClient(k8s.CoreV1Api);

function uploadSecret(applicationId, configJSON) {
  const yamlString = `apiVersion: v1
kind: Secret
metadata:
  name: instance-${applicationId}
type: generic
stringData:
  production.json: |
    ${configJSON}`;

  const yamlSecret = k8s.loadYaml(yamlString);

  return k8sApi.deleteNamespacedSecret('default', applicationId)
    .then(null, () => {
      // ignore errors
    })
    .then(() => k8sApi.createNamespacedSecret('default', yamlSecret));
}

module.exports = uploadSecret;
```

**Environment (please complete the following information):**
 - OS: linux
 - NodeJS Version: 16 (but I tried 12 and 14 to see if updating would fix this)
 - Cloud runtime: GKE kubernetes pod (without cluster credentials)

**Additional context**
nothing that I can think of right now, let me know if there are any techniques I can use to debug this 👍

**Comment by brendandburns** [comment]
What does your Kubeconfig file look like? And where are you placing it in the container's file system.

This is likely because the CA certificate isn't getting loaded correctly but it's hard to know why without additional details.

If you could add your kubeconfig (after removing any sensitive/private info) that would be useful.

**Comment by mansona** [comment]
Sure thing! I don't know how helpful this is going to be for you but hopefully it will spark more questions 😂 

```yaml
apiVersion: v1
    kind: Config
    clusters:
    - name: my-cluster-name
      cluster:
        server: https://1.2.3.4 # obviously not my real ip :) 
        certificate-authority-data: stuff # i don't know if this is actually sensitive - it is a big long base64 encoded thing
    users:
    - name: user-name-kubernetes-gsa
      user:
        auth-provider:
          name: gcp
    contexts:
    - context:
        cluster: my-cluster-name
        user: user-name-kubernetes-gsa
      name: user-name-kubernetes
    current-context: user-name-kubernetes
```

Let me know if you have any questions
