### ISSUE TITLE
v1PodDisruptionBudgetSpec.maxUnavailable should be Integer or String

### ISSUE THREAD

**Issue by alex-bezek** [kubernetes-client/javascript#738]
In the Pod Disruption Budget Spec, the maxUnavailable and minAvailable attributes are set as objects. The documented yaml format is this
```
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: zk-pdb
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      app: zookeeper
```

The k8s API docs show it should be `IntOrString` https://kubernetes.io/docs/reference/kubernetes-api/policy-resources/pod-disruption-budget-v1/#PodDisruptionBudgetSpec

Other libraries do set it to an IntOrString as well
* https://github.com/fabric8io/kubernetes-client/blob/00a28cc9d69a552589b8aa268e0db4fb5e9186cf/kubernetes-model-generator/kubernetes-model-policy/src/main/resources/schema/validation-schema.json#L999
* https://github.com/kubernetes/client-go/blob/master/applyconfigurations/policy/v1/poddisruptionbudgetspec.go#L29

Is this intentional or a quirk of javascript? Or are these attributes typed incorrectly?
