### ISSUE TITLE
Client does not respect exec plug in - EKS

### ISSUE THREAD

**Issue by Ahmad-RW** [kubernetes-client/javascript#891]
**Describe the bug**
My kubeconfig has exec plugin under user. It works fine with kubectl but everything returns unauthorised error from the client. After changing user.exec to user.token (By running aws eks get-token ...etc and obtaining a token manually). The client works perfectly.
** Client Version **
`0.16.3`

** Server Version **
`v1.23.10-eks-15b7512`

**To Reproduce**
- create EKS
- obtain kubeconfig
- make sure it has exec plugin
- use the client to and consume kubeconfig by using `loadFromFile`
- try to create a deployment
- unauthorized response is returned
- if the same is done with kubectl it'll pass

**Expected behavior**
it should carry the same behaviour as kubectl 

** Example Code**
```
      const kc = new KubeConfig()
      kc.loadFromFile('./kube-config.aws.yaml');
      const k8sCoreApi = kc.makeApiClient(k8s.CoreV1Api);
      const k8sAppApi = kc.makeApiClient(k8s.AppsV1Api);
      await k8sAppApi.createNamespacedDeployment(
        'default',
        someConfig
      );
```
if I do this 
```
kc.users[0].token = 'some valid token generated manually'
```
it works fine and deployment gets created ok

**Environment (please complete the following information):**
 - OS: MacOs but running everything on Docker container 
 - NodeJS Version: 16
 - Cloud runtime: AWS EKS

**Additional context**
I believe the library does not execute aws eks get-token. and updating the kubeconfig with the token produced

**Comment by brendandburns** [comment]
Can you share the contents of your kubeconfig file (remove any secrets first).

The client does have an exec plugin support (https://github.com/kubernetes-client/javascript/blob/master/src/exec_auth.ts) and so in theory this should work.

**Comment by Ahmad-RW** [comment]
> Can you share the contents of your kubeconfig file (remove any secrets first).
> 
> The client does have an exec plugin support (https://github.com/kubernetes-client/javascript/blob/master/src/exec_auth.ts) and so in theory this should work.

Sorry for the late reply. There you go : 
```
---
apiVersion: v1
clusters:
- cluster:
    server: XXXX
    certificate-authority-data: XXXX
  name: kubernetes
contexts:
- context:
    cluster: kubernetes
    user: aws
  name: aws
current-context: aws
kind: Config
users:
- name: aws
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      command: aws
      args:
      - eks
      - get-token
      - "--cluster-name"
      - myCluster
      env:
      - name: KUBERNETES_EXEC_INFO
        value: '{"apiVersion": "client.authentication.k8s.io/v1beta1"}'

```
