### ISSUE TITLE
Error: unable to verify the first certificate (UNABLE_TO_VERIFY_LEAF_SIGNATURE)

### ISSUE THREAD

**Issue by seunggs** [kubernetes-client/javascript#949]
**Describe the bug**
Trying to access Kubernetes API server via JS client in a node server running in EKS cluster, but keep getting `Error: unable to verify the first certificate (UNABLE_TO_VERIFY_LEAF_SIGNATURE)` error. 

`kubectl` works fine inside the pod.

** Client Version **
e.g. `0.18.0`

** Server Version **
e.g. `1.24.7`

**To Reproduce**
Inside EKS cluster, create a service that runs a node server. In the node server, use JS client to try and access Kubernetes API server using the following code (more or less):
```
const k8s = require('@kubernetes/client-node')
const kc = new k8s.KubeConfig()
kc.loadFromFile(kubeconfigPath)
const podLog = await axios.get(`${kc.getCurrentCluster().server}/api/v1/namespaces/${namespace}/pods/${podName}/log?container=${containerName}`)
```

**Expected behavior**
Should be able to get the pod log back.

**Environment (please complete the following information):**
 - OS: Linux
 - NodeJS Version: 16
 - Cloud runtime: AWS EKS

**Comment by seunggs** [comment]
I added `NODE_EXTRA_CA_CERTS` to specify the cert path in the default ServiceAccount and it seems to have solved this issue, but now I’m getting 401 unauthorized error. 

The default ServiceAccount is bound via ClusterRoleBinding to a ClusterRole in `app-dev` namespace where the node server is running and I'm not sure what's set up incorrectly?

aws-auth ConfigMap:
```
apiVersion: v1
data:
  mapRoles: |
    - rolearn: 'arn:aws:iam::xxxxx:role/DeveloperRole-efa2d74'
      username: developer-user
      groups:
        - prod-group
...
```

ClusterRoleBinding:
```
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: DeveloperRole
subjects:
- kind: ServiceAccount
  name: default
  namespace: app-dev
...
```

DeveloperRole ClusterRole:
```
rules:
- apiGroups:
  - ""
  - extensions
  - apps
  - batch
  - autoscaling
  - rbac.authorization.k8s.io
  resources:
  - '*'
  verbs:
  - '*'
```
