### ISSUE TITLE
How to Connect to K8S programatically ? (Created via eksctl in AWS)

### ISSUE THREAD

**Issue by rohitcoder** [kubernetes-client/javascript#968]
Hi There,

I was checking documentation and I found there is a way to connect to K8S using different methods, can you tell me how we can connect to K8S using EKS configured via ``eksctl`` command and ``aws configure``.

I can see a ``/.kube/config`` file, but what values i need to connect to different k8S clusters created using this same method? My end goal is to have a web application where user can put their creds and they can connect to k8s
Below is sample of ``/.kube/config`` file, my PC has ``aws configure`` done. The server won't have this config, what kind of creds i should ask from user?

Sample of my kube config
```yaml
apiVersion: v1
clusters:
- cluster:
    certificate-authority-data: A_LONG_STRING_HERE
    server: https://XXXXXXXXXXXXX.gr7.ap-south-1.eks.amazonaws.com
  name: xxxxxxx.ap-south-1.eksctl.io
contexts:
- context:
    cluster: xxxxxx.ap-south-1.eksctl.io
    user: iam-root-account@xxxxx.ap-south-1.eksctl.io
  name: iam-root-account@xxxxx.ap-south-1.eksctl.io
- context:
    cluster: xxxx.ap-south-1.eksctl.io
    user: user@xxxxx.ap-south-1.eksctl.io
  name: user@xxxxx.ap-south-1.eksctl.io
current-context: iam-root-account@xxxxx.ap-south-1.eksctl.io
kind: Config
preferences: {}
users:
- name: iam-root-account@xxxxxx.ap-south-1.eksctl.io
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - token
      - -i
      - xxxxxxx
      command: aws-iam-authenticator
      env:
      - name: AWS_STS_REGIONAL_ENDPOINTS
        value: regional
      - name: AWS_DEFAULT_REGION
        value: ap-south-1
      provideClusterInfo: false
- name: <NAME>@xxxxx.ap-south-1.eksctl.io
  user:
    exec:
      apiVersion: client.authentication.k8s.io/v1beta1
      args:
      - token
      - -i
      - xxxxxxxx
      command: aws-iam-authenticator
      env:
      - name: AWS_STS_REGIONAL_ENDPOINTS
        value: regional
      - name: AWS_DEFAULT_REGION
        value: ap-south-1
      provideClusterInfo: false
```
